### ISSUE TITLE
Does not seem to work with new version of matplotlib (2.1.2)

### ISSUE THREAD

**Issue by orendar** [jmcarpenter2/parfit#7]
Hey,

When updating the library through pip, it automatically updated my matplotlib from 2.1.1 to 2.1.2, and when trying to import parfit it throws a matplotlib-related import error 'cannot import name 'TransformedPatchPath''. I can confirm this is related to the update of matplotlib because when I uninstalled matplotlib and reinstalled 2.1.1, parfit works again.

**Comment by jmcarpenter2** [comment]
Hi @orendar I just updated parfit and then subsequently upgraded my install, which in turn updated matplotlib to 2.1.2 and I'm not experiencing this issue. Can you please try to recreate it and provide details on the specifics that produced the error? This would be greatly appreciated so I can fix it for everyone :) Thanks!
